/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/vr_gallery.glb -o src/components/Gallery.jsx -r public 
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Gallery(props) {
  const { nodes, materials } = useGLTF(
    'https://webflow-public-assets.s3.amazonaws.com/testing/vr_gallery.glb'
  )
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh
            geometry={nodes.VR_Gallery_VR_Gallery_0_1.geometry}
            material={materials.VR_Gallery}
          />
          <mesh
            geometry={nodes.VR_Gallery_VR_Gallery_0_2.geometry}
            material={materials['Material.001']}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(
  'https://webflow-public-assets.s3.amazonaws.com/testing/vr_gallery.glb'
)
