/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/metrosubway_station_interior.glb -o src/components/LevelTwo.jsx -r public 
Author: ETBENO (https://sketchfab.com/yulaflibiskuvi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/metrosubway-station-interior-14f5a6534607450d82583e0aa0ed345b
Title: Metro/Subway Station Interior
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF(
    'https://webflow-public-assets.s3.amazonaws.com/testing/metrosubway_station_interior.glb'
  )
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.586}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_4.geometry}
            material={materials['Material.003']}
            position={[-8.011, 0.015, 4.068]}
            scale={14.515}
          />
          <mesh
            geometry={nodes.Object_6.geometry}
            material={materials['Material.007']}
            position={[-0.961, 8.153, 0.584]}
            rotation={[0, 0, -Math.PI]}
            scale={[-6.994, 0.534, 5.16]}
          />
          <mesh
            geometry={nodes.Object_8.geometry}
            material={materials['Material.007']}
            position={[-7.657, 8.153, 9.84]}
            rotation={[0, 0, -Math.PI]}
            scale={[-8.54, 0.534, 4.916]}
          />
          <mesh
            geometry={nodes.Object_10.geometry}
            material={materials['Material.007']}
            position={[-19.858, 8.153, 11.596]}
            rotation={[0, 0, -Math.PI]}
            scale={[-3.982, 0.534, 3.251]}
          />
          <mesh
            geometry={nodes.Object_12.geometry}
            material={materials['Material.001']}
            position={[-8.297, 8.153, 2.871]}
            rotation={[0, 0.926, -Math.PI]}
            scale={[-4.877, 0.534, 3.286]}
          />
          <mesh
            geometry={nodes.Object_14.geometry}
            material={materials['Material.005']}
            position={[1.63, 7.355, 0]}
            scale={[0.496, 0.656, 4.37]}
          />
          <mesh
            geometry={nodes.Object_16.geometry}
            material={materials['Material.005']}
            position={[-8.349, 7.355, 6.372]}
            scale={[0.496, 0.656, 8.334]}
          />
          <mesh
            geometry={nodes.Object_18.geometry}
            material={materials['Material.005']}
            position={[-4.458, 7.355, 4.967]}
            scale={[0.496, 0.656, 9.258]}
          />
          <mesh
            geometry={nodes.Object_20.geometry}
            material={materials['Material.005']}
            position={[-11.704, 7.355, 8.685]}
            scale={[0.496, 0.656, 6.066]}
          />
          <mesh
            geometry={nodes.Object_22.geometry}
            material={materials['Material.007']}
            position={[-8.559, 4.633, 0.393]}
            scale={[0.16, 3.351, 0.16]}
          />
          <mesh
            geometry={nodes.Object_24.geometry}
            material={materials['Material.007']}
            position={[5.045, 6.604, -3.746]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.082, 6.135, 0.082]}
          />
          <mesh
            geometry={nodes.Object_26.geometry}
            material={materials['Material.007']}
            position={[-10.498, 6.583, 2.879]}
            rotation={[0.012, 0.941, -1.578]}
            scale={[0.082, 8.039, 0.097]}
          />
          <mesh
            geometry={nodes.Object_28.geometry}
            material={materials['Material.007']}
            position={[-19.195, 6.563, 9.354]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.082, 4.056, 0.082]}
          />
          <mesh
            geometry={nodes.Object_30.geometry}
            material={materials.material_0}
            position={[-1.909, 6.479, 0.446]}
            rotation={[1.571, 0, 0]}
            scale={[0.402, 3.52, 0.402]}
          />
          <mesh
            geometry={nodes.Object_32.geometry}
            material={materials['Material.009']}
            position={[-1.909, 6.352, 0.446]}
            rotation={[1.571, 0, 0]}
            scale={[0.269, 3.288, 0.219]}
          />
          <mesh
            geometry={nodes.Object_34.geometry}
            material={materials['Material.002']}
            position={[-1.909, 6.478, 4.025]}
            rotation={[1.571, 0, 0]}
            scale={[0.402, 3.52, 0.402]}
          />
          <mesh
            geometry={nodes.Object_36.geometry}
            material={materials['Material.001']}
            position={[-1.909, 6.479, -3.131]}
            rotation={[1.571, 0, 0]}
            scale={[0.402, 3.52, 0.402]}
          />
          <mesh
            geometry={nodes.Object_38.geometry}
            material={materials['Material.002']}
            position={[-10.224, 6.24, 12.383]}
            rotation={[1.571, 0, 0]}
            scale={[0.402, 3.52, 0.402]}
          />
          <mesh
            geometry={nodes.Object_40.geometry}
            material={materials['Material.001']}
            position={[-10.224, 6.24, 5.226]}
            rotation={[1.571, 0, 0]}
            scale={[0.402, 3.52, 0.402]}
          />
          <mesh
            geometry={nodes.Object_42.geometry}
            material={materials.material_0}
            position={[-10.224, 6.24, 8.804]}
            rotation={[1.571, 0, 0]}
            scale={[0.402, 3.52, 0.402]}
          />
          <mesh
            geometry={nodes.Object_44.geometry}
            material={materials['Material.009']}
            position={[-10.224, 6.075, 8.804]}
            rotation={[1.571, 0, 0]}
            scale={[0.269, 3.288, 0.138]}
          />
          <mesh
            geometry={nodes.Object_46.geometry}
            material={materials['Black.metal']}
            position={[-2.073, 6.293, -3.162]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.018}
          />
          <mesh
            geometry={nodes.Object_48.geometry}
            material={materials['Black.metal']}
            position={[-2.073, 6.293, 4.03]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.018}
          />
          <mesh
            geometry={nodes.Object_50.geometry}
            material={materials['Black.metal']}
            position={[-10.233, 6.109, 5.225]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.018}
          />
          <mesh
            geometry={nodes.Object_52.geometry}
            material={materials['Black.metal']}
            position={[-10.233, 6.109, 12.434]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.018}
          />
          <mesh
            geometry={nodes.Object_54.geometry}
            material={materials['Material.011']}
            position={[-6.797, 6.264, 7.589]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.754, 0.754, 1.258]}
          />
          <mesh
            geometry={nodes.Object_56.geometry}
            material={materials['Material.007']}
            position={[-6.861, 7.647, 6.919]}
            rotation={[-Math.PI, 0, 0]}
            scale={[-0.077, 0.753, 0.077]}
          />
          <mesh
            geometry={nodes.Object_58.geometry}
            material={materials['Material.022']}
            position={[-10.955, 3.92, 2.709]}
            rotation={[Math.PI / 2, 0, -0.968]}
            scale={[1.25, 0.808, 1.758]}
          />
          <mesh
            geometry={nodes.Object_60.geometry}
            material={materials['Material.014']}
            position={[-11.148, 5.78, 2.577]}
            rotation={[0.175, 0.934, -1.705]}
            scale={[0.069, 1.344, 0.288]}
          />
          <mesh
            geometry={nodes.Object_62.geometry}
            material={materials['Material.015']}
            position={[-17.315, 4.445, 13.934]}
            rotation={[Math.PI / 2, 0, Math.PI]}
            scale={[1.507, 1.507, 2.072]}
          />
          <mesh
            geometry={nodes.Object_64.geometry}
            material={materials['Material.016']}
            position={[3.032, 4.389, 3.965]}
            rotation={[Math.PI / 2, 0, Math.PI]}
            scale={[1.247, 1.247, 1.666]}
          />
          <mesh
            geometry={nodes.Object_66.geometry}
            material={materials['Material.019']}
            position={[-5.428, 2.004, -2.797]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[0.515, 0.515, 0.86]}
          />
          <mesh
            geometry={nodes.Object_68.geometry}
            material={materials['Material.021']}
            position={[-7.031, 6.723, 6.674]}
            rotation={[Math.PI / 2, 0, Math.PI / 2]}
            scale={0.235}
          />
          <mesh
            geometry={nodes.Object_70.geometry}
            material={materials['Material.021']}
            position={[-6.691, 6.349, 7.553]}
            rotation={[Math.PI / 2, 0, Math.PI / 2]}
            scale={[-0.235, 0.235, 0.235]}
          />
          <mesh
            geometry={nodes.Object_72.geometry}
            material={materials['Material.006']}
            position={[-11.807, 3.912, 2.879]}
            scale={[5.979, 6, 4.061]}
          />
          <mesh
            geometry={nodes.Object_74.geometry}
            material={materials['Material.006']}
            position={[3.015, 2.785, 4.638]}
            scale={[5.979, 6, 4.061]}
          />
          <mesh
            geometry={nodes.Object_76.geometry}
            material={materials['Material.006']}
            position={[-19.343, 4.445, 8.65]}
            scale={[5.979, 6, 4.061]}
          />
          <mesh
            geometry={nodes.Object_78.geometry}
            material={materials['Material.006']}
            position={[0.521, 4.187, 9.004]}
            scale={[5.979, 6, 4.061]}
          />
          <mesh
            geometry={nodes.Object_80.geometry}
            material={materials['Material.006']}
            position={[0.234, 3.966, -4.511]}
            scale={[5.979, 6, 4.061]}
          />
          <mesh
            geometry={nodes.Object_82.geometry}
            material={materials['Material.002']}
            position={[0.012, 0.378, 9.004]}
            scale={[5.979, 6, 4.061]}
          />
          <mesh
            geometry={nodes.Object_84.geometry}
            material={materials['Material.002']}
            position={[3.015, 0.38, 3.992]}
            scale={[5.979, 6, 4.061]}
          />
          <mesh
            geometry={nodes.Object_86.geometry}
            material={materials['Material.002']}
            position={[-11.487, 0.349, 14.147]}
            scale={[5.979, 6, 4.061]}
          />
          <mesh
            geometry={nodes.Object_88.geometry}
            material={materials['Material.002']}
            position={[0.012, 0.36, -4.13]}
            scale={[5.979, 6, 4.061]}
          />
          <mesh
            geometry={nodes.Object_90.geometry}
            material={materials['Material.002']}
            position={[-9.211, 0.354, -0.131]}
            scale={[5.979, 6, 4.061]}
          />
          <mesh
            geometry={nodes.Object_92.geometry}
            material={materials['Material.002']}
            position={[-13.481, 0.347, 5.585]}
            scale={[5.979, 6, 4.061]}
          />
          <mesh
            geometry={nodes.Object_94.geometry}
            material={materials['Material.002']}
            position={[-19.343, 0.348, 8.829]}
            scale={[5.979, 6, 4.061]}
          />
          <mesh
            geometry={nodes.Object_96.geometry}
            material={materials['Material.006']}
            position={[-17.233, 4.16, 14.371]}
            scale={[5.979, 6, 4.061]}
          />
          <mesh
            geometry={nodes.Object_98.geometry}
            material={materials['Material.006']}
            position={[-5.718, 4.16, 14.371]}
            scale={[5.979, 6, 4.061]}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(
  'https://webflow-public-assets.s3.amazonaws.com/testing/metrosubway_station_interior.glb'
)
